In [30]:
import numpy as np

In [31]:
from sklearn.datasets import load_iris

In [32]:
X = load_iris()['data']
y = load_iris()['target']

In [33]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [54]:
def relu(x) :
    return np.maximum(0,x)

In [34]:
def softmax(x):
    c = np.max(x,axis=1).reshape(-1,1)
    x = x-c
    return np.exp(x)/np.sum(np.exp(x),axis=1).reshape(-1,1)

In [35]:
def categorical_crossentropy(t,y):
    return np.mean(-t*np.log(y))

In [36]:
def make_one(x):
    result = np.zeros((x.size,np.unique(x).size))
    for idx1,idx2 in enumerate(x):
        result[idx1,idx2] = 1
    return result

In [37]:
X.shape

(150, 4)

In [38]:
y = make_one(y)

In [39]:
input_shape = X.shape[1:]
output_shape = y.shape[1:]

In [40]:
W1 = np.random.randn(4,50)
b1 = np.zeros(50)
W2 = np.random.randn(50,3)
b2 = np.zeros(3)

In [41]:
def predict(x):
    W1 = np.random.randn(4,50)
    b1 = np.zeros(50)
    W2 = np.random.randn(50,3)
    b2 = np.zeros(3)
    layer1 = np.dot(x,W1) + b1
    z1 = sigmoid(layer1)
    layer2 = np.dot(z1,W2) + b2
    out = softmax(layer2)
    return out

In [42]:
def numerical_gradient(f,x):
    h = 1e-4
    grad = np.zeros_like(x)
    it = np.nditer(x,flags=['multi_index'],op_flags=['readwrite'])
    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        x[idx] = tmp_val + h
        fxh = f(x)
        x[idx] = tmp_val - h
        fx = f(x)
        grad[idx] = (fxh-fx)/(2*h)
        it.iternext()
        x[idx] = tmp_val
    return grad

In [43]:
f = lambda x : x[0]**2 + x[1]**3

In [44]:
numerical_gradient(f,np.array([2.,3.]))

array([ 4.        , 27.00000001])

In [45]:
# numerical_gradient(W_loss,W1)

In [46]:
def gradient_descent(x,t):
    y = predict(x)
    W_loss = lambda W: categorical_crossentropy(y,t)
    dW1 = numerical_gradient(W_loss,W1)
    db1 = numerical_gradient(W_loss,b1)
    dW2 = numerical_gradient(W_loss,W2)
    db2 = numerical_gradient(W_loss,b2)
    W1 -= dW1*lr
    b1 -= db1*lr
    W2 -= dW2*lr
    b2 -= db2*lr

In [47]:
layer1 = np.dot(X,W1) + b1
z1 = sigmoid(layer1)
layer2 = np.dot(z1,W2) + b2
out = softmax(layer2)
lr = 1e-4
W_loss = lambda W: categorical_crossentropy(y,out)
dW1 = numerical_gradient(W_loss,W1)
db1 = numerical_gradient(W_loss,b1)
dW2 = numerical_gradient(W_loss,W2)
db2 = numerical_gradient(W_loss,b2)
W1 -= dW1*lr
b1 -= db1*lr
W2 -= dW2*lr
b2 -= db2*lr


In [48]:
categorical_crossentropy(y,out)

0.5277144766684667

In [49]:
categorical_crossentropy(y,out)

0.5277144766684667

In [50]:
y_hat = predict(X)
categorical_crossentropy(y,y_hat)

1.7951979850172142

In [67]:
a = {}
a['w1'] = a
len(a)

1

In [148]:
def prob(x) :
    return x+0.0000

IndentationError: expected an indented block (645767825.py, line 1)

In [144]:
class Network:
    def __init__(self):
        self.layer = {}
        
    def add(self, x1, x2, activation) :
        activation_dict = {
            'sigmoid' : sigmoid,
            'relu' : relu,
            'softmax' : softmax,
            'prob' : prob
        }
        w = 'W'+str((int(len(self.layer)/3) + 1))
        b = 'b'+str((int(len(self.layer)/3) + 1))
        a = 'activation'+str((int(len(self.layer)/3) + 1))
        
        self.layer[w] = np.random.randn(x1,x2)
        self.layer[b] = np.zeros(x2)
        self.layer[a] = activation_dict[activation]
        
    def predict(self,x):
        length = int(len(self.layer)/3)+1
        y = x.copy()
        for i in range(1, length):
            w = 'W'+ str(i)
            b = 'b'+ str(i)
            a = 'activation'+str(i)
            y = np.dot(y,self.layer[w]) + self.layer[b]
            y = self.layer[a](y)
        return y
    
    def loss(self,x,t):
        y = self.predict(x)
        err = categorical_crossentropy(t,y) 
        self.err = err
        return self.err
    
    def accuracy(self,x,t):
        y = self.predict(x)
        y = np.argmax(y,axis=1)
        t = np.argmax(t,axis=1)
        self.acc = np.sum(y==t)/t.size
        return self.acc
    
    def gradient(self,x,t):
        #self.loss(x,t)
        lr = 1e-4
        W_loss = lambda W : self.loss(x,t)
        length = int(len(self.layer)/3) + 1
        for i in range(1,length) :
            w = 'W' +str(i)
            b = 'b' +str(i)
            dW = numerical_gradient(W_loss,self.layer[w])
            db = numerical_gradient(W_loss,self.layer[b])
            self.layer[w] -= dW*lr
            self.layer[b] -= db*lr
        
        
    def fit(self,x,t,epochs) :
        history = {}
        accuracy = []
        loss = []
        for epoch in range(epochs) :
            self.gradient(x,t)
            loss.append[self.err]
            accuracy.append(self.accuracy(x,t))
            if epoch % 100 == 0:
                print(f'loss : {self.err} === accuracy : {self.accuracy(x,t)}')
                history['accuarcy'] = accuracy
                history['loss'] = loss
        pass

In [145]:
model1 = Network(0.5)
model2 = Network(1.)

In [146]:

model1.add(4,10,'relu')
model1.add(10,3,'softmax')


In [ ]:

model2.add(4,10,'relu')
model2.add(10,3,'softmax')


In [ ]:
model2.layer['W1'] = model1.layer['W1'] * 2.
model2.layer['W2'] = model1.layer['W2'] * 2.
model2.layer['W3'] = model1.layer['W3'] * 2.  

In [ ]:
out = np.dot(X,np.random.randn(4,3))
np.sum(prob(out)

In [ ]:
model1.fit(X,y,10000)

In [147]:
model.predict(X).shape

1
2
3


(150, 3)

In [113]:
model.layer

{'W1': array([[ 0.90793929,  1.30757094,  0.65659901, -0.33709326, -0.0430854 ,
         -0.20843107, -0.13677681,  1.1185398 ,  0.74909805,  1.07810955,
         -0.10908887, -0.94382716,  0.89599918,  0.71247817,  1.15404231,
          0.16204402,  0.57034186,  0.57516782,  1.46684478, -0.77667778,
         -1.30520251,  1.43782806,  0.18068703,  1.60041617,  0.3093977 ,
         -0.2955283 ,  1.31436218,  0.31597576,  0.92683732, -0.90515725,
         -0.77520425, -1.25073576, -0.0937023 ,  1.25052883, -0.20730657,
         -0.73741297, -0.93195463, -0.30804302,  1.36681048, -0.30619679,
         -0.22493087, -1.15342662,  1.37790834, -0.12066998,  0.82858632,
         -0.47846432, -0.18548743, -0.43736344,  0.28862536,  0.37621815],
        [ 1.22357939,  0.30522077, -2.04485586,  0.09695515, -1.52973397,
         -0.23254839,  0.45483865,  0.58127967, -0.10122169, -0.45135461,
          0.97185712, -0.06142887, -0.54275956, -1.63352525,  0.48514671,
          0.23506298, -0.160806

In [117]:
model.layer['activation1']
# for _,v in model.layer.items():
#     print(v)

TypeError: 'function' object is not subscriptable

In [63]:
# model.fit(X,y)

TypeError: fit() missing 1 required positional argument: 'epochs'

In [58]:
X[[8]]

array([[4.4, 2.9, 1.4, 0.2]])

In [60]:
np.argmax(model.predict(X[[8]]))

0

In [59]:
y[8]

array([1., 0., 0.])

In [64]:
epochs = 10000
for epoch in range(epochs): 
    model.gradient(X,y)
    if epoch % 100 == 0:
        print(f'loss : {model.err} === accuracy : {model.accuracy(X,y)}')

loss : 2.787337548633541 === accuracy : 0.34
loss : 1.4966590826928798 === accuracy : 0.36666666666666664
loss : 1.3211960116220043 === accuracy : 0.38
loss : 1.2403061794077743 === accuracy : 0.36666666666666664
loss : 1.1702030177298566 === accuracy : 0.37333333333333335
loss : 1.1014161305804828 === accuracy : 0.37333333333333335
loss : 1.0329860479844193 === accuracy : 0.38
loss : 0.9651221643373933 === accuracy : 0.37333333333333335
loss : 0.8980705735089805 === accuracy : 0.36666666666666664
loss : 0.8328974613504448 === accuracy : 0.36666666666666664
loss : 0.7694463656309752 === accuracy : 0.37333333333333335
loss : 0.707701393555339 === accuracy : 0.38
loss : 0.6480497571085804 === accuracy : 0.38666666666666666
loss : 0.5910278453350861 === accuracy : 0.38666666666666666
loss : 0.5374131364976144 === accuracy : 0.38666666666666666
loss : 0.4874790037972219 === accuracy : 0.3933333333333333
loss : 0.44137288662885876 === accuracy : 0.4
loss : 0.399560661645761 === accuracy : 0

KeyboardInterrupt: 

In [ ]:
model = Network()

In [ ]:
model.gradient(X,y)

TypeError: 'numpy.float64' object is not callable

In [149]:
from 
from keras.models import Sequential
from keras.datasets import mnist
from keras.layers import Dense, Flatten


ModuleNotFoundError: No module named 'keras'