In [1]:
import numpy as np

In [3]:
arr = np.array([[1,2,3],[4,5,6]]) # 2x3
print(arr)
print(arr.reshape(3,2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [4]:
print(arr.reshape(6,1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [5]:
print(arr.reshape(1,6))

[[1 2 3 4 5 6]]


In [14]:
print(arr.reshape(3,1,2))

[[[1 2]]

 [[3 4]]

 [[5 6]]]


In [9]:
arr1 = np.array([1,2,3,4,5,6])
arr1.shape

(6,)

In [13]:
print(arr.reshape(6))

[1 2 3 4 5 6]


In [15]:
print(arr.reshape(-1,2))

[[1 2]
 [3 4]
 [5 6]]


In [16]:
print(arr.reshape(2,-1))

[[1 2 3]
 [4 5 6]]


In [19]:
tensor = np.array(range(1,37))    # shape (3, 3, 4)

In [20]:
print(tensor.reshape(3,3,4))

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]


### tensor 배열을 2차원 배열로 변형시켜봅니다. * 열의 개수는 9

In [21]:
print(tensor.reshape( -1,9 ))

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36]]


In [22]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
print(arr.flatten())

[1 2 3 4 5 6]


In [25]:
print(tensor.reshape(3,3,4).flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


In [26]:
print(np.arange(30))    # np.array(range(30))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [27]:
print(np.arange(0,10,2))   # (start, end, step)

[0 2 4 6 8]


In [28]:
print(np.arange(-2,2,0.5))

[-2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5]


In [29]:
print(np.arange(10,0,-1))

[10  9  8  7  6  5  4  3  2  1]


In [31]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [32]:
# 100 ~ 190 ,10  shape(2, 5)

print(np.arange(100,191,10).reshape(2, 5))

[[100 110 120 130 140]
 [150 160 170 180 190]]


In [34]:
# -2 ~ 2 , 0.5  3차원 

print(np.arange(-2,2.1,0.5).reshape(1,3,3))

[[[-2.  -1.5 -1. ]
  [-0.5  0.   0.5]
  [ 1.   1.5  2. ]]]


In [35]:
print(np.zeros(shape=(5,),dtype=np.int8))

[0 0 0 0 0]


In [36]:
print(np.zeros((5),np.int8))

[0 0 0 0 0]


In [39]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [43]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
matrix = np.arange(24).reshape(4,6)

In [45]:
matrix

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [46]:
print(np.zeros_like(matrix))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [47]:
matrix = np.arange(-2,2,0.2).reshape(2,10)

In [48]:
matrix

array([[-2.0000000e+00, -1.8000000e+00, -1.6000000e+00, -1.4000000e+00,
        -1.2000000e+00, -1.0000000e+00, -8.0000000e-01, -6.0000000e-01,
        -4.0000000e-01, -2.0000000e-01],
       [-4.4408921e-16,  2.0000000e-01,  4.0000000e-01,  6.0000000e-01,
         8.0000000e-01,  1.0000000e+00,  1.2000000e+00,  1.4000000e+00,
         1.6000000e+00,  1.8000000e+00]])

In [50]:
print(np.ones_like(matrix))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [51]:
matrix = np.arange(30).reshape(5,6)
matrix

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [53]:
print(np.empty_like(matrix))

[[3801155 5570652 6619251 7536754 6357084 7143524]
 [7209065 3014748 7340137 7602297 7274600 6029422]
 [7471216 6684783 7077993 6226021 6619236 6357094]
 [7078005 6029428 6881384 7602291 7471215 3014777]
 [7405683 6881388 6619252 7798829 7077985       0]]


In [55]:
print(np.identity(5,dtype=np.str_))

[['1' '' '' '' '']
 ['' '1' '' '' '']
 ['' '' '1' '' '']
 ['' '' '' '1' '']
 ['' '' '' '' '1']]


In [56]:
print(np.identity(2,dtype=np.int8))

[[1 0]
 [0 1]]


In [57]:
print(np.eye(5,dtype=np.int8))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [59]:
print(np.eye(5, k = -1))

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [60]:
print(np.eye(5, M=10, k=-1))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]


In [63]:
print(np.eye(5, M = 3, k = -1))

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [68]:
print(np.full((2,5),3))

[[3 3 3 3 3]
 [3 3 3 3 3]]


In [70]:
np.ones((3,3)) * 3

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [71]:
np.full((3,3),3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [72]:
np.random.randint(6)

3

In [73]:
import random

In [79]:
random.randint(0,10)

0

In [77]:
np.random.randint(1,20,2)

array([19,  9])

In [90]:
print(np.random.rand(2,5))

[[0.02780726 0.78063277 0.53676588 0.51211452 0.98261074]
 [0.8730283  0.08451291 0.58182508 0.04175429 0.03595128]]


In [91]:
print(np.random.randn(2,5))

[[-0.15798613 -2.90165792 -2.56112748 -0.62310919 -0.16857252]
 [ 0.70753857 -0.20352874  0.71725836  1.16715957  0.06103641]]


In [92]:
matrix = np.arange(1,7).reshape(2,3)
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
matrix.sum()

21

In [95]:
print(matrix.sum(axis=0))

[5 7 9]


In [96]:
print(matrix.sum(axis=1))

[ 6 15]


In [97]:
tensor = np.arange(1,19).reshape(3,2,3)
print(tensor)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [101]:
print(tensor.sum(axis=2))

[[ 6 15]
 [24 33]
 [42 51]]


In [107]:
tensor.sum(axis=0)   # np.sum(tensor)

array([[21, 24, 27],
       [30, 33, 36]])

In [106]:
np.sum(tensor,axis=0)

array([[21, 24, 27],
       [30, 33, 36]])

In [108]:
print(matrix)

[[1 2 3]
 [4 5 6]]


In [111]:
print(matrix.mean(axis=0))

[2.5 3.5 4.5]


In [112]:
print(matrix.mean(axis=1))

[2. 5.]


In [113]:
print(matrix.std())

1.707825127659933


In [115]:
print(matrix)

[[1 2 3]
 [4 5 6]]


In [114]:
print(matrix.std(axis=0))

[1.5 1.5 1.5]


In [118]:
import math

In [122]:
math.sqrt( ( (2.5-1)*(2.5-1) + (2.5-4)*(2.5-4))      / 2   )

1.5

In [124]:
vector = np.array([np.random.randint(1,100) for n in range(5)])

In [125]:
print(vector)

[78 72 24 25 15]


In [126]:
print(np.sort(vector))

[15 24 25 72 78]


In [127]:
print(np.sort(vector)[::-1])

[78 72 25 24 15]


In [128]:
[np.random.randint(1,100) for n in range(5)]

[60, 16, 57, 58, 64]

In [134]:
x = 3
[x for i in range(5) if x == i]

[3]

In [130]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [131]:
a = []
for i in range(5):
    a.append(i)
print(a)

[0, 1, 2, 3, 4]


In [135]:
list_ = [1,2,3,4,5,6,7,8,9,10]

list2_ = [num * 3  for num in list_ if num % 2 == 1]
list2_

[3, 9, 15, 21, 27]

In [136]:
matrix = np.array([np.random.randint(1,100) for n in range(20)]).reshape(4,5)
print(matrix)

[[48 82 94 37 96]
 [47 47 51  2 77]
 [47 27 71 59 24]
 [95 75 51 46 10]]


In [139]:
print(np.sort(matrix,axis=1))

[[37 48 82 94 96]
 [ 2 47 47 51 77]
 [24 27 47 59 71]
 [10 46 51 75 95]]


In [138]:
print(np.sort(matrix,axis=0))

[[47 27 51  2 10]
 [47 47 51 37 24]
 [48 75 71 46 77]
 [95 82 94 59 96]]


In [141]:
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])

print(np.vstack([vector1, vector2]))

[[1 2 3]
 [4 5 6]]


In [144]:
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])

print(np.hstack([vector1, vector2]))

[1 2 3 4 5 6]


In [143]:
vector1   [1 2 3] + [4 5 6] = [1 2 3 4 5 6]

array([[1],
       [2],
       [3]])

In [154]:
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])

print(np.concatenate([vector1, vector2]))

[1 2 3 4 5 6]


In [156]:
vector1 = np.array([[1,2,3]])
vector2 = np.array([[4,5,6]])

print(np.concatenate([vector1, vector2],axis=0))

[[1 2 3]
 [4 5 6]]


In [159]:
vector1 = np.array([[1,2,3],[1,2,3]]).reshape(3,2)
vector2 = np.array([4,5,6]).reshape(3,1)

print(np.concatenate([vector1, vector2], axis = 1))

[[1 4]
 [2 5]
 [3 6]]


In [163]:
matrix1 = np.array([[1,2,3],[1,2,3]]).reshape(3,2)
vector2 = np.array([4,5,6]).reshape(3,1)

print(np.concatenate([matrix1, vector2], axis = 1))

[[1 2 4]
 [3 1 5]
 [2 3 6]]


In [164]:
matrix3 = np.array([[5, 6]])
print(matrix3)

[[5 6]]


In [165]:
print(matrix3.transpose())

[[5]
 [6]]


In [167]:
print(matrix3.shape, matrix3.transpose().shape)

(1, 2) (2, 1)


In [168]:
print(matrix3.T)

[[5]
 [6]]


In [170]:
np.array([5, 6]).T.shape

(2,)

In [173]:
np.array([[[5, 6]]]).T.shape

(2, 1, 1)

In [175]:
matrix1 = np.array([[1,2],[3,4]]).reshape(2,2)

In [176]:
print(np.concatenate([matrix1, matrix3],axis=0))

[[1 2]
 [3 4]
 [5 6]]


In [177]:
print(np.concatenate([matrix1, matrix3],axis=1))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [178]:
print(np.concatenate([matrix1, matrix3.T], axis=1))

[[1 2 5]
 [3 4 6]]


In [179]:
b = np.array([[1,2,3,4],
              [2,3,4,1],
              [3,4,1,2]])

In [180]:
print(np.argmin(b, axis=1))

[0 3 2]


In [181]:
print(np.argmin(b, axis=0))

[0 0 2 1]


In [182]:
a = np.arange(1,11)
b = np.array([3,4,5,6])

print(a[b])

[4 5 6 7]
