In [1]:
import numpy as np

In [2]:
list1 = [1,2,3]
list2 = [4,5,6]
print(list1 + list2)

[1, 2, 3, 4, 5, 6]


In [3]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 + arr2)

[5 7 9]


In [4]:
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(11,17).reshape(2,3)
print(arr1 + arr2)

[[12 14 16]
 [18 20 22]]


In [5]:
print(arr1 - arr2)

[[-10 -10 -10]
 [-10 -10 -10]]


In [6]:
print(arr1 * arr2)

[[11 24 39]
 [56 75 96]]


In [7]:
print(arr2 / arr1)

[[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]]


In [8]:
print(arr1 ** arr2)

[[         1       4096    1594323]
 [ 268435456  452807053 -683606016]]


In [10]:
print(arr2 // arr1)

[[11  6  4]
 [ 3  3  2]]


In [11]:
print(arr2 % arr1)

[[0 0 1]
 [2 0 4]]


In [12]:
arr3 = np.arange(10).reshape(5,2)
arr4 = np.arange(10).reshape(2,5)
print(arr3 + arr4)

ValueError: operands could not be broadcast together with shapes (5,2) (2,5) 

In [16]:
scalar = 10
vector = np.array([1,2,3])

print(scalar / vector)

[10.          5.          3.33333333]


In [20]:
scalar = 10
matrix = np.array([[1,2,3],[4,5,6]])

print(scalar % matrix)

[[0 0 1]
 [2 0 4]]


In [21]:
matrix = np.arange(1,10).reshape(3,3)
vector = np.arange(11,14).reshape(1,3)
print(matrix + vector)

[[12 14 16]
 [15 17 19]
 [18 20 22]]


In [22]:
matrix = np.arange(1,10).reshape(3,3)
vector = np.arange(11,14).reshape(3,1)
print(matrix + vector)

[[12 13 14]
 [16 17 18]
 [20 21 22]]


In [23]:
arr1 = np.array([[1,2,3]])
arr2 = np.array([1,2,3]).reshape(3,1)

print(arr1)
print(arr2)

[[1 2 3]]
[[1]
 [2]
 [3]]


In [24]:
print(arr1 + arr2)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [27]:
np.broadcast(arr1, arr2)

In [28]:
arr3 = np.array([1,2,3])
arr4 = np.array([4,5,6])

In [29]:
np.broadcast(arr3, arr4)