In [1]:
import numpy as np

In [2]:
n = np.random.randn(3,5)
print(n)

[[ 0.53059301  1.03789048 -1.2484819   1.66990217 -0.65732666]
 [-0.69940247 -0.88872504 -0.91353899  0.26905104  0.21578227]
 [ 1.03148934 -0.30352477  1.32050385 -0.07147526  0.15874125]]


In [3]:
n.tofile('n.npy')

In [4]:
m = np.fromfile('C:/STUDY/Python/n.npy')  # shape(3,5)
print(m)

[ 0.53059301  1.03789048 -1.2484819   1.66990217 -0.65732666 -0.69940247
 -0.88872504 -0.91353899  0.26905104  0.21578227  1.03148934 -0.30352477
  1.32050385 -0.07147526  0.15874125]


In [5]:
np.save('n1.npy',n)
m1 = np.load('n1.npy')
print(m1)

[[ 0.53059301  1.03789048 -1.2484819   1.66990217 -0.65732666]
 [-0.69940247 -0.88872504 -0.91353899  0.26905104  0.21578227]
 [ 1.03148934 -0.30352477  1.32050385 -0.07147526  0.15874125]]


In [6]:
# n.tofile  >  n.npy
# np.load('n.npy')
np.load('n.npy')

ValueError: Cannot load file containing pickled data when allow_pickle=False

In [7]:
np.savetxt('n.txt',n)

In [8]:
np.loadtxt('./data/n.txt')

array([[ 0.53059301,  1.03789048, -1.2484819 ,  1.66990217, -0.65732666],
       [-0.69940247, -0.88872504, -0.91353899,  0.26905104,  0.21578227],
       [ 1.03148934, -0.30352477,  1.32050385, -0.07147526,  0.15874125]])

In [16]:
np.savetxt('n.csv',n, delimiter=  ',' )

In [17]:
np.loadtxt('n.csv', delimiter=',', dtype=str)

array([['5.305930085592863721e-01', '1.037890484223708221e+00',
        '-1.248481898085396891e+00', '1.669902172463105128e+00',
        '-6.573266610255257270e-01'],
       ['-6.994024732143292455e-01', '-8.887250367472011581e-01',
        '-9.135389886706444251e-01', '2.690510400871876651e-01',
        '2.157822715821887394e-01'],
       ['1.031489340528059628e+00', '-3.035247702613738108e-01',
        '1.320503850307412241e+00', '-7.147525743705127055e-02',
        '1.587412483501480231e-01']], dtype='<U25')

In [13]:
np.savetxt('n.csv',n, delimiter=  '***' )

In [14]:
np.loadtxt('n.csv', delimiter='***')

array([[ 0.53059301,  1.03789048, -1.2484819 ,  1.66990217, -0.65732666],
       [-0.69940247, -0.88872504, -0.91353899,  0.26905104,  0.21578227],
       [ 1.03148934, -0.30352477,  1.32050385, -0.07147526,  0.15874125]])

In [18]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
np.savetxt('data.csv',arr,delimiter=',')

In [21]:
np.loadtxt('data.csv',delimiter=',',dtype=np.int8)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]], dtype=int8)

In [24]:
np.loadtxt('./data/06_data1.txt', dtype=np.str_)

array([['1', '15', '14', '4'],
       ['12', '6', '7', '9'],
       ['8', '10', '11', '5'],
       ['13', '3', '2', '16']], dtype='<U2')

In [25]:
np.loadtxt('./data/06_data1.txt',delimiter='\t', dtype=np.str_)

array([['1', '15', '14', '4'],
       ['12', '6', '7', '9'],
       ['8', '10', '11', '5'],
       ['13', '3', '2', '16']], dtype='<U2')

In [29]:
arr2 = np.loadtxt('./data/06_data2.txt', delimiter=',', dtype=np.int8)

In [30]:
print(arr2)

[[ 1 15 14  4]
 [12  6  7  9]
 [ 8 10 11  5]
 [13  3  2 16]]


In [31]:
np.savetxt('data.csv',np.arange(1,26,dtype=np.int8).reshape(5,5),delimiter=',')

In [32]:
np.loadtxt('data.csv',delimiter=',')

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [35]:
data = np.loadtxt('./data/ex1_지역별전기요금.csv', delimiter=',', dtype=int)

In [36]:
print(data[  :5  ,  : ])

[[      1  565082     273   27177]
 [      2 2827233     444   45111]
 [      3 1144913     289   29043]
 [      4 1131034     230   22436]
 [      5  380425     391   38020]]


In [37]:
data.shape

(17, 4)

In [38]:
print(np.unique( data[:,0]  ))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [45]:
print(np.sort(data,axis=0))

[[      1   49394     221   22180]
 [      2  258605     230   22436]
 [      3  323151     249   25120]
 [      4  380425     268   26899]
 [      5  425659     273   27177]
 [      6  565082     282   27901]
 [      7  584500     285   28556]
 [      8  634696     289   29043]
 [      9  668623     344   32331]
 [     10  726699     353   35245]
 [     11  734723     361   35470]
 [     12  742285     364   36274]
 [     13  947300     366   36569]
 [     14 1131034     391   38020]
 [     15 1144913     398   40049]
 [     16 2737725     444   45111]
 [     17 2827233     580   57091]]


In [42]:
print(data[:,1].argsort())

[ 9 14 10  4  6  0 16 13  5 12 11 15  7  3  2  8  1]


In [43]:
print(data[data[:,1].argsort()])

[[     10   49394     580   57091]
 [     15  258605     221   22180]
 [     11  323151     353   35470]
 [      5  380425     391   38020]
 [      7  425659     344   32331]
 [      1  565082     273   27177]
 [     17  584500     268   26899]
 [     14  634696     285   28556]
 [      6  668623     364   35245]
 [     13  726699     249   25120]
 [     12  734723     398   40049]
 [     16  742285     282   27901]
 [      8  947300     366   36274]
 [      4 1131034     230   22436]
 [      3 1144913     289   29043]
 [      9 2737725     361   36569]
 [      2 2827233     444   45111]]


In [48]:
print(data[ data[:,1].argsort()[::-1] ])

[[      2 2827233     444   45111]
 [      9 2737725     361   36569]
 [      3 1144913     289   29043]
 [      4 1131034     230   22436]
 [      8  947300     366   36274]
 [     16  742285     282   27901]
 [     12  734723     398   40049]
 [     13  726699     249   25120]
 [      6  668623     364   35245]
 [     14  634696     285   28556]
 [     17  584500     268   26899]
 [      1  565082     273   27177]
 [      7  425659     344   32331]
 [      5  380425     391   38020]
 [     11  323151     353   35470]
 [     15  258605     221   22180]
 [     10   49394     580   57091]]


In [50]:
# 전국 대상 가구수의 합

data[:,1].sum()    # np.sum(data[:,1])

14882047

In [51]:
# 가구당 평균 전력 사용량의 전국 평균값

np.mean(data[:,2])      # data[:,2].mean()

335.1764705882353

In [53]:
round(np.mean(data[:,2]), 2)

335.18

In [60]:
# 무식하게 평균 구하기
e_sum = np.sum(data[:,2])
e_sum

n_rows = data.shape[0]
n_rows

print('가구당 평균 전력 사용량의 전국 평균값 :', round(e_sum / n_rows , 2)   )

가구당 평균 전력 사용량의 전국 평균값 : 335.18


In [61]:
avg_ = np.mean(data[:,2])
avg_

335.1764705882353

In [66]:
print(data[data[:,2] > avg_][ : , :2 ])

[[      2 2827233]
 [      5  380425]
 [      6  668623]
 [      7  425659]
 [      8  947300]
 [      9 2737725]
 [     10   49394]
 [     11  323151]
 [     12  734723]]


In [70]:
data[data[:,2] > avg_][ :, [0,3]]

array([[    2, 45111],
       [    5, 38020],
       [    6, 35245],
       [    7, 32331],
       [    8, 36274],
       [    9, 36569],
       [   10, 57091],
       [   11, 35470],
       [   12, 40049]])

In [71]:
data = np.loadtxt('./data/ex2_전년대비_시도별_교통사망사고.csv', delimiter=',', dtype=float)
print(data)

[[ 2.014e+03  1.000e+00  2.180e+02  4.800e+00 -9.000e+00 -4.000e+00]
 [ 2.014e+03  2.000e+00  8.720e+02  1.900e+01 -4.500e+01 -4.900e+00]
 [ 2.014e+03  3.000e+00  4.010e+02  8.700e+00 -4.500e+01 -1.010e+01]
 [ 2.014e+03  4.000e+00  4.640e+02  1.010e+01 -4.100e+01 -8.100e+00]
 [ 2.014e+03  5.000e+00  9.900e+01  2.200e+00 -5.000e+00 -4.800e+00]
 [ 2.014e+03  6.000e+00  1.820e+02  4.000e+00  1.900e+01  1.170e+01]
 [ 2.014e+03  7.000e+00  9.900e+01  2.200e+00  8.000e+00  8.800e+00]
 [ 2.014e+03  8.000e+00  1.630e+02  3.600e+00 -4.700e+01 -2.240e+01]
 [ 2.014e+03  9.000e+00  3.860e+02  8.400e+00  1.400e+01  3.800e+00]
 [ 2.014e+03  1.000e+01  2.000e+01  4.000e-01  0.000e+00  0.000e+00]
 [ 2.014e+03  1.100e+01  1.030e+02  2.200e+00 -1.600e+01 -1.340e+01]
 [ 2.014e+03  1.200e+01  1.440e+02  3.100e+00 -6.000e+00 -4.000e+00]
 [ 2.014e+03  1.300e+01  4.000e+02  8.700e+00 -3.500e+01 -8.000e+00]
 [ 2.014e+03  1.400e+01  3.170e+02  6.900e+00 -3.500e+01 -9.900e+00]
 [ 2.014e+03  1.500e+01  8.600e+01

In [72]:
data.shape

(17, 6)

In [73]:
np.unique(data[:,1])

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17.])

In [74]:
print(data[:3,[0,2,3] ])

[[2014.   218.     4.8]
 [2014.   872.    19. ]
 [2014.   401.     8.7]]


In [85]:
print(data[ 7])

[2014.     8.   163.     3.6  -47.   -22.4]


In [84]:
print(data[data[:,1] == 8])

[[2014.     8.   163.     3.6  -47.   -22.4]]


In [88]:
print('전국 사고 발생건수의 총합 :',data[:,2].sum())

전국 사고 발생건수의 총합 : 4583.0


In [90]:
print('전국 사고 발생건수의 평균 :',round(data[:,2].mean(), 3 ) )

전국 사고 발생건수의 평균 : 269.588


In [91]:
max(data[:,4])

19.0

In [93]:
print(data[data[:,4] == max(data[:,4])])

[[2014.     6.   182.     4.    19.    11.7]]


In [94]:
np.argmax(data[:,4])

5

In [96]:
print(data[ np.argmax(data[:,4]) ])

[2014.     6.   182.     4.    19.    11.7]


In [97]:
min(data[:,5])

-22.4

In [100]:
print(data[data[:,5] == min(data[:,5])])

[[2014.     8.   163.     3.6  -47.   -22.4]]


In [102]:
print(data[ np.argmin(data[:,5]) ])

[2014.     8.   163.     3.6  -47.   -22.4]


In [109]:
data2 = data[data[:,2] >= 400]
data2

array([[ 2.014e+03,  2.000e+00,  8.720e+02,  1.900e+01, -4.500e+01,
        -4.900e+00],
       [ 2.014e+03,  3.000e+00,  4.010e+02,  8.700e+00, -4.500e+01,
        -1.010e+01],
       [ 2.014e+03,  4.000e+00,  4.640e+02,  1.010e+01, -4.100e+01,
        -8.100e+00],
       [ 2.014e+03,  1.300e+01,  4.000e+02,  8.700e+00, -3.500e+01,
        -8.000e+00]])

In [111]:
print(data2[ :  ,[1,2,4,5]])

[[  2.  872.  -45.   -4.9]
 [  3.  401.  -45.  -10.1]
 [  4.  464.  -41.   -8.1]
 [ 13.  400.  -35.   -8. ]]


In [112]:
print(data[data[:,2] >= 400][:,[1,2,4,5]])

[[  2.  872.  -45.   -4.9]
 [  3.  401.  -45.  -10.1]
 [  4.  464.  -41.   -8.1]
 [ 13.  400.  -35.   -8. ]]
